# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ab88a726318b55f9af16d1a37f2a3a9e902327848a95aad6cff93c0e29cfa8ac0a8cf5fd8cea402e385b93cf532557c8b42a10c18e646ab84efedf703fb6a8

test:
  secret_key_base: 3fff685f46f7d6229b5aba8a22ab9e278308f85f73cd73aa3758d601afa090b43680ab56dc19706064bf222a27586eec03dd9ab7cfadc9ee442c7c8b182c20d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
